# Generated by Django 5.0.3 on 2024-03-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_rename_adjusted_close_price_stockdata_adj_close_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('report_type', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_of_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_investment_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_interest_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=15)),
                ('non_interest_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_non_operating_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('depreciation_amortization', models.DecimalField(decimal_places=2, max_digits=15)),
                ('income_before_tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('income_tax_expense', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_and_debt_expense', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_income_from_continuing_operations', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comprehensive_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
