# Generated by Django 5.0.3 on 2024-03-19 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_incomestatementdata_cogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStockData',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sector', models.CharField(choices=[('Industrials', 'Industrials'), ('Financials', 'Financials'), ('Information Technology', 'Information Technology'), ('Health Care', 'Health Care'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Consumer Staples', 'Consumer Staples'), ('Real Estate', 'Real Estate'), ('Utilities', 'Utilities'), ('Materials', 'Materials'), ('Energy', 'Energy'), ('Communication Services', 'Communication Services')], max_length=25)),
                ('headquarters', models.CharField(max_length=255)),
                ('date_added', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStockPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adj_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('dividend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_price_data', to='stocks.basestockdata')),
            ],
            options={
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='StockData',
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='report_type',
            field=models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=9),
        ),
        migrations.AddField(
            model_name='incomestatementdata',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_statement_data', to='stocks.basestockdata'),
        ),
        migrations.AlterUniqueTogether(
            name='incomestatementdata',
            unique_together={('stock', 'report_type', 'date')},
        ),
        migrations.RemoveField(
            model_name='incomestatementdata',
            name='symbol',
        ),
    ]
