# Generated by Django 5.0.3 on 2024-03-23 13:37

import django.db.models.deletion
import stocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_basestockdata_monthlystockpricedata_delete_stockdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomestatementdata',
            name='cogs',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='comprehensive_income',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='cost_of_revenue',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='depreciation',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='depreciation_amortization',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='ebit',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='ebitda',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='gross_profit',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='income_before_tax',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='income_tax_expense',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='interest_and_debt_expense',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='interest_expense',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='interest_income',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='net_income',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='net_income_from_continuing_operations',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='net_interest_income',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='net_investment_income',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='non_interest_income',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='operating_income',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='other_non_operating_income',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatementdata',
            name='total_revenue',
            field=stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='BalanceSheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=9)),
                ('date', models.DateField()),
                ('total_assets', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_current_assets', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_and_cash_equivalents_at_carrying_value', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_and_short_term_investments', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('inventory', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_net_receivables', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_non_current_assets', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('property_plant_equipment', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('accumulated_depreciation_amortization_ppe', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('intangible_assets', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('intangible_assets_excluding_goodwill', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('goodwill', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('investments', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('long_term_investments', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('short_term_investments', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_current_assets', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_non_current_assets', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_liabilities', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_current_liabilities', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_accounts_payable', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deferred_revenue', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_debt', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('short_term_debt', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_non_current_liabilities', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('capital_lease_obligations', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('long_term_debt', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_long_term_debt', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('long_term_debt_noncurrent', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('short_long_term_debt_total', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_current_liabilities', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_non_current_liabilities', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_shareholder_equity', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('treasury_stock', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('retained_earnings', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('common_stock', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('common_stock_shares_outstanding', stocks.models.StockDecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheet_data', to='stocks.basestockdata')),
            ],
            options={
                'unique_together': {('stock', 'report_type', 'date')},
            },
        ),
    ]
