# Generated by Django 5.0.3 on 2024-03-23 18:14

import django.db.models.deletion
import stocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_basestockdata_cik_basestockdata_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=9)),
                ('date', models.DateField()),
                ('operating_cashflow', stocks.models.StockIntegerField(blank=True, null=True)),
                ('payments_for_operating_activities', stocks.models.StockIntegerField(blank=True, null=True)),
                ('proceeds_from_operating_activities', stocks.models.StockIntegerField(blank=True, null=True)),
                ('change_in_operating_liabilities', stocks.models.StockIntegerField(blank=True, null=True)),
                ('change_in_operating_assets', stocks.models.StockIntegerField(blank=True, null=True)),
                ('depreciation_depletion_and_amortization', stocks.models.StockIntegerField(blank=True, null=True)),
                ('capital_expenditures', stocks.models.StockIntegerField(blank=True, null=True)),
                ('change_in_receivables', stocks.models.StockIntegerField(blank=True, null=True)),
                ('change_in_inventory', stocks.models.StockIntegerField(blank=True, null=True)),
                ('profit_loss', stocks.models.StockIntegerField(blank=True, null=True)),
                ('cashflow_from_investment', stocks.models.StockIntegerField(blank=True, null=True)),
                ('cashflow_from_financing', stocks.models.StockIntegerField(blank=True, null=True)),
                ('proceeds_from_repayments_of_short_term_debt', stocks.models.StockIntegerField(blank=True, null=True)),
                ('payments_for_repurchase_of_common_stock', stocks.models.StockIntegerField(blank=True, null=True)),
                ('payments_for_repurchase_of_equity', stocks.models.StockIntegerField(blank=True, null=True)),
                ('payments_for_repurchase_of_preferred_stock', stocks.models.StockIntegerField(blank=True, null=True)),
                ('dividend_payout', stocks.models.StockIntegerField(blank=True, null=True)),
                ('dividend_payout_common_stock', stocks.models.StockIntegerField(blank=True, null=True)),
                ('dividend_payout_preferred_stock', stocks.models.StockIntegerField(blank=True, null=True)),
                ('proceeds_from_issuance_of_common_stock', stocks.models.StockIntegerField(blank=True, null=True)),
                ('proceeds_from_issuance_of_long_term_debt_and_capital_securities_net', stocks.models.StockIntegerField(blank=True, null=True)),
                ('proceeds_from_issuance_of_preferred_stock', stocks.models.StockIntegerField(blank=True, null=True)),
                ('proceeds_from_repurchase_of_equity', stocks.models.StockIntegerField(blank=True, null=True)),
                ('proceeds_from_sale_of_treasury_stock', stocks.models.StockIntegerField(blank=True, null=True)),
                ('change_in_cash_and_cash_equivalents', stocks.models.StockIntegerField(blank=True, null=True)),
                ('change_in_exchange_rate', stocks.models.StockIntegerField(blank=True, null=True)),
                ('net_income', stocks.models.StockIntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_data', to='stocks.basestockdata')),
            ],
            options={
                'unique_together': {('stock', 'report_type', 'date')},
            },
        ),
    ]
