# Generated by Django 5.0.3 on 2024-03-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_cashflowdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflowdata',
            old_name='proceeds_from_issuance_of_long_term_debt_and_capital_securities_net',
            new_name='proceeds_issuance_long_term_debt_capital_sec_net',
        ),
    ]
