# Generated by Django 5.0.3 on 2024-03-23 18:26

import django.db.models.deletion
import stocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_rename_proceeds_from_issuance_of_long_term_debt_and_capital_securities_net_cashflowdata_proceeds_iss'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=9)),
                ('date', models.DateField()),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('reported_eps', stocks.models.StockIntegerField(blank=True, null=True)),
                ('estimated_eps', stocks.models.StockIntegerField(blank=True, null=True)),
                ('surprise', stocks.models.StockIntegerField(blank=True, null=True)),
                ('surprise_percentage', stocks.models.StockIntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings_data', to='stocks.basestockdata')),
            ],
            options={
                'unique_together': {('stock', 'report_type', 'date', 'reported_date')},
            },
        ),
    ]
