# Generated by Django 5.0.3 on 2024-03-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_rename_date_added_basestockdata_date_added_to_sp500_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningscalendardata',
            name='estimate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
