# Generated by Django 5.0.3 on 2024-03-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_alter_earningscalendardata_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestockdata',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
