# Generated by Django 5.0.3 on 2024-03-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_alter_basestockdata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=5, max_digits=20)),
                ('interval', models.CharField(max_length=10)),
                ('per_capita', models.BooleanField()),
            ],
            options={
                'verbose_name': 'US Real GDP (per Capita and aggregate)',
                'verbose_name_plural': 'US Real GDP (per Capita and aggregate) Data',
                'unique_together': {('date', 'interval', 'per_capita')},
            },
        ),
    ]
