# Generated by Django 5.0.3 on 2024-03-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_alter_gdpdata_options_alter_gdpdata_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdpdata',
            name='interval',
            field=models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=10),
        ),
    ]
