# Generated by Django 5.0.3 on 2024-03-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_alter_gdpdata_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                'verbose_name': 'Effective Federal Funds Rate',
                'verbose_name_plural': 'Effective Federal Funds Rate Data',
                'ordering': ['-date'],
            },
        ),
    ]
