# Generated by Django 5.0.3 on 2024-03-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_alter_ffrdata_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'verbose_name': 'Consumer Price Index for All Urban Consumers (1982-1984=1)',
                'verbose_name_plural': 'Consumer Price Index (1982-1984=1) Data',
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='DurablesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Durable Goods Orders',
                'verbose_name_plural': 'Durable Goods Orders Data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InflationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'verbose_name': 'Inflation Rate',
                'verbose_name_plural': 'Inflation Rate Data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NonfarmPayrollData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Nonfarm Payroll Total People Employed',
                'verbose_name_plural': 'Nonfarm Payroll Total People Employed Data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RetailSalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Retail Sales',
                'verbose_name_plural': 'Retail Sales Data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UnemploymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'verbose_name': 'Unemployment Rate',
                'verbose_name_plural': 'Unemployment Rate Data',
                'ordering': ['-date'],
            },
        ),
        migrations.RenameField(
            model_name='ffrdata',
            old_name='rate',
            new_name='value',
        ),
    ]
