# Generated by Django 5.0.3 on 2024-03-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_cpidata_durablesdata_inflationdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryYieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maturity_months', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'verbose_name': 'Treasury Yield',
                'verbose_name_plural': 'Treasury Yields',
                'unique_together': {('date', 'maturity_months')},
            },
        ),
    ]
