# Generated by Django 5.0.3 on 2024-03-24 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_alter_treasuryyielddata_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=7)),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adj_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('dividend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_data', to='stocks.basestockdata')),
            ],
            options={
                'unique_together': {('stock', 'date', 'interval')},
            },
        ),
        migrations.DeleteModel(
            name='MonthlyStockPriceData',
        ),
    ]
