# Generated by Django 5.0.3 on 2024-03-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0024_stockpricedata_delete_monthlystockpricedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earningsdata',
            old_name='date',
            new_name='fiscal_date_ending',
        ),
        migrations.AlterUniqueTogether(
            name='earningsdata',
            unique_together={('stock', 'report_type', 'fiscal_date_ending', 'reported_date')},
        ),
    ]
