# Generated by Django 5.0.3 on 2024-03-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0025_rename_date_earningsdata_fiscal_date_ending_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EarningsData',
        ),
    ]
