# Generated by Django 5.0.3 on 2024-03-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0028_alter_earningsdata_estimated_eps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningsdata',
            name='estimated_eps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='earningsdata',
            name='reported_eps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='earningsdata',
            name='surprise',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='earningsdata',
            name='surprise_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
    ]
