# Generated by Django 5.0.3 on 2024-03-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0029_alter_earningsdata_estimated_eps_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EarningsData',
        ),
    ]
