# Generated by Django 5.0.3 on 2024-03-28 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0030_delete_earningsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=9)),
                ('fiscal_date_ending', models.DateField()),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('reported_eps', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('estimated_eps', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('surprise', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('surprise_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings_data', to='stocks.basestockdata')),
            ],
            options={
                'unique_together': {('stock', 'report_type', 'fiscal_date_ending', 'reported_date')},
            },
        ),
    ]
