# Generated by Django 5.0.3 on 2024-03-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0031_earningsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningscalendardata',
            name='fiscal_date_ending',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earningscalendardata',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
