# Generated by Django 5.0.3 on 2024-03-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0032_alter_earningscalendardata_fiscal_date_ending_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='earningscalendardata',
            unique_together={('stock', 'fiscal_date_ending')},
        ),
        migrations.RemoveField(
            model_name='earningscalendardata',
            name='current_date',
        ),
    ]
