# Generated by Django 5.0.3 on 2024-03-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0033_alter_earningscalendardata_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningscalendardata',
            name='horizon_months',
        ),
    ]
